# Generated by Django 4.0.4 on 2022-05-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=60)),
                ('Contraseña', models.CharField(max_length=15)),
            ],
        ),
    ]
