# Generated by Django 4.0.4 on 2022-05-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFuncionario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nombre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
